apiVersion: v1
kind: Service
metadata:
  name: api-svc
  annotations:
    alb.ingress.kubernetes.io/security-groups: default
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
