name: Setup Cloud

on:
  push:
    branches: 
      - main

jobs:
 
  setup-terraform:

    runs-on: ubuntu-latest
    
    steps:
            
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2        
        
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Destroy
      id: destory
      run: terraform destroy
      continue-on-error: true
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true    

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: true

  setup-kubernetes:

    runs-on: ubuntu-latest    
    needs: setup-terraform
    steps:
            
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        mask-aws-account-id: 'no'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1    
 
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      id: install-kubectl

    - name: Update KubeConfig
      shell: bash
      run: |
        aws eks update-kubeconfig --name fiap-tech-challenge-infra-k8s --region=us-east-2 
    
    - name: Deploy MongoDB
      id: deploy-mongodb
      run: |        
        cd ./kubernetes/mongodb
        kubectl apply -f mongodb-pv.yaml
        kubectl apply -f mongodb-pvc.yaml
        kubectl apply -f mongodb-deployment.yaml
        kubectl apply -f mongodb-svc.yaml
        kubectl rollout restart deployment mongo-deployment

    - name: Get SQS url
      id: sqs-url
      run: |        
        export PRODUCAO_QUEUE=$(echo $(aws sqs list-queues) | jq '.QueueUrls'[0])
        export PRODUCAO_QUEUE=$(echo $PRODUCAO_QUEUE|tr -d '\"')
        export PRODUCAO_QUEUE="PRODUCAO_QUEUE=$PRODUCAO_QUEUE" 
        echo $PRODUCAO_QUEUE >> $GITHUB_OUTPUT

    - name: Deploy API Default
      id: deploy-api-default
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |        
        export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}/fiap-tech-challenge-api:latest        
        export DB_HOST_API=${{ secrets.DB_HOST_API }}
        export DB_PASS=${{ secrets.DB_PASS }}
        cd ./kubernetes/metrics-server
        kubectl apply -f components.yaml
        cd ../api-go
        envsubst < secrets.yaml | kubectl apply -f -
        envsubst < api-deployment.yaml | kubectl apply -f -
        kubectl apply -f api-hpa.yaml
        kubectl apply -f api-svc.yaml           
        export API_URL="API_URL=http://$(kubectl get svc api-svc -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'):3000"        
        echo $API_URL >> $GITHUB_OUTPUT
        kubectl rollout restart deployment api-deployment

    - name: Deploy API Producao
      id: deploy-api-producao
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |        
        export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}/fiap-tech-challenge-api-producao:latest        
        export DB_HOST_PRODUCAO=${{ secrets.DB_HOST_PRODUCAO }}
        export DB_PASS=${{ secrets.DB_PASS }}
        export PRODUCAO_QUEUE=$(echo -n ${{ steps.sqs-url.outputs.PRODUCAO_QUEUE }} | base64 -w 0)
        export AWS_REGION=$(echo -n "us-east-2" | base64) 
        cd ./kubernetes/api-producao
        envsubst < secrets.yaml | kubectl apply -f -
        envsubst < deployment.yaml | kubectl apply -f -
        kubectl apply -f hpa.yaml
        kubectl apply -f svc.yaml
        export PRODUCAO_URL="PRODUCAO_URL=http://$(kubectl get svc api-producao-svc -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'):3000"        
        echo $PRODUCAO_URL >> $GITHUB_OUTPUT
        kubectl rollout restart deployment api-producao-deployment

    - name: Deploy API Pedidos
      id: deploy-api-pedidos
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |        
        export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}/fiap-tech-challenge-api-pedidos:latest        
        export API_URL=$(echo -n ${{ steps.deploy-api-default.outputs.API_URL }} | base64 -w 0)        
        cd ./kubernetes/api-pedidos
        envsubst < secrets.yaml | kubectl apply -f -
        envsubst < deployment.yaml | kubectl apply -f -
        kubectl apply -f hpa.yaml
        kubectl apply -f svc.yaml
        export PEDIDOS_URL="PEDIDOS_URL=http://$(kubectl get svc api-pedidos-svc -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'):3000"        
        echo $PEDIDOS_URL >> $GITHUB_OUTPUT
        kubectl rollout restart deployment api-pedidos-deployment

    - name: Deploy API Pagamentos
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |        
        export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}/fiap-tech-challenge-api-pagamentos:latest        
        export DB_HOST_PAGAMENTOS=${{ secrets.DB_HOST_PAGAMENTOS }}
        export DB_PASS=${{ secrets.DB_PASS }}
        export PRODUCAO_URL=$(echo -n ${{ steps.deploy-api-producao.outputs.PRODUCAO_URL }} | base64 -w 0)
        export PEDIDOS_URL=$(echo -n ${{ steps.deploy-api-pedidos.outputs.PEDIDOS_URL }} | base64 -w 0)        
        export PRODUCAO_QUEUE=$(echo -n ${{ steps.sqs-url.outputs.PRODUCAO_QUEUE }} | base64 -w 0)
        export AWS_REGION=$(echo -n "us-east-2" | base64) 
        cd ./kubernetes/api-pagamentos
        envsubst < secrets.yaml | kubectl apply -f -
        envsubst < deployment.yaml | kubectl apply -f -
        kubectl apply -f hpa.yaml
        kubectl apply -f svc.yaml
        kubectl rollout restart deployment api-pagamentos-deployment
        