name: Setup Cloud

on:
  push:
    branches: [ "main" ]

jobs:
 
  setup-terraform:

    runs-on: ubuntu-latest

    steps:
            
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Destroy
      id: destory
      run: terraform destroy
      continue-on-error: true
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true    

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: true

  setup-kubernetes:

    runs-on: ubuntu-latest
    needs: setup-terraform
    
    steps:
            
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Install kubectl
      uses: azure/setup-kubectlv@2.0
      with:
        version: 'v1.24.0'
      id: install

    - name: Deploy      
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}/fiap-tech-challenge-api:latest
        cd ./metrics-server
        kubectl apply -f components.yaml
        cd ../api-go
        envsubst < api-deployment.yaml | kubectl apply -f -
        kubectl apply -f api-hpa.yaml
        kubectl apply -f api-svc.yaml

